### ISSUE TITLE
suggestion: remove `_util/assert.ts`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno_std#2849] opened 2022-11-07 06:42 UTC
Please read #2846 before reading this. I suggest moving `std/testing/asserts.ts` to either an `std/testing/asserts` or `std/asserts` folder with an assertion-per-file. The folder would look more like `std/fs`.

Indeed, there is a large number of assertions, meaning there will be a large number of files. However, I think this is worth it to gain leaner assertion-related dependencies.

The files will have to be moved out, and then `std/testing/asserts.ts` functions deprecated. It'd be a bit of work, but I'd be happy to do it.

**Comment by bartlomieju** [comment] 2022-11-07 12:17
Strong -1 from me; this module is probably one of the most popular modules from std, it would be a huge disruptive change. I don't think it's worth it, since very often you need more than one assertion. Having to import them from separate files will be cumbersome for no obvious gain.

**Comment by lino-levan** [comment] 2022-11-07 16:59
Personally, I agree with @bartlomieju on this one. I think that if this was better for DX even if it was a disruptive change it could be seriously considered (deno itself was a disruptive change, less so now that we have pretty good compat). I struggle to see how splitting up assertions into different files would give *any* advantage to anything, especially DX?

>However, I think this is worth it to gain leaner assertion-related dependencies.

I'd be curious to hear you elaborate on your point about this. Maybe I'm misunderstanding something and this is more valuable than I currently think.

**Comment by iuioiua** [comment] 2022-11-07 20:10
Non-test code is supposed to use `assert` from `_util/assert.ts` to:
1. Avoid importing other unneeded code from `testing/asserts.ts`.
2. Avoid browser compatibility issues from `testing/asserts.ts`.
However, now, `testing/asserts.ts` is browser compatible. I suggest breaking the code up to cater to number 1.

Again, what's gained is that importing unnecessary assertions can be avoided. There can also exist a `mod.ts` so that multiple assertions can be imported if needed. This would remove the need for `_util/assert.ts`.

**Comment by iuioiua** [comment] 2022-11-07 20:16
> Non-test code is supposed to use `assert` from `_util/assert.ts`

My question is: why is `assert` the only assertion that this rule applies to? Other assertions are used in non-test code.

Alternatively, these other assertions could move into `_util/asserts.ts`. It would be less disruptive.

<img width="406" alt="image" src="https://user-images.githubusercontent.com/29347852/200405699-c9e81b75-c5f9-4ccd-999c-4a4144e7e183.png">

**Comment by iuioiua** [comment] 2022-11-07 21:57
Again, check out #2846. These are my points exactly. Perhaps, I closed the PR prematurely.

**Comment by lino-levan** [comment] 2022-11-07 22:05
> I doubt /testing/asserts.ts is used such many places except testing/examples. In my view, non-test code should only use _util/assert.ts because it has less dependencies.

@kt3k, could you elaborate on this statement? I guess having `_util/assert.ts` is a tradeoff between code duplication and "less dependencies", but I don't quite understand what you mean by this.

In my opinion we really want to minimize code duplication, so I'd be in favor of removing `_util/assert.ts` and swapping it for `test/assert.ts`. What is the counterpoint on this?

**Comment by iuioiua** [comment] 2022-11-07 22:22
`_util/assert.ts` has only one function - `assert`. So `_util/assert.ts` has fewer dependencies (only one assertion) than `testing/asserts.ts` (all the assertions). Importing from `_util/assert.ts` makes other code within the codebase lighter than `testintg/asserts.ts`.

To be clear, I also support removing code duplication because of the confusion it can bring. I also support having fewer dependencies. This suggestion was supposed to satisfy both criteria. I'm open, though.

**Comment by lino-levan** [comment] 2022-11-07 22:31
I don't understand how it makes other code in the codebase "lighter". Are you suggesting that the one-time cost of downloading `testing/assert` outweighs the benefits of no code duplication? It is quite literally only ~23kb.

**Comment by iuioiua** [comment] 2022-11-07 22:34
That's the justification. Check out denoland/deno#5838.

**Comment by kt3k** [comment] 2022-11-08 03:45
In my view these 2 are not duplicate of the same thing. `_util/assert.ts` is for checking internal state of program execution, and `testing/assets.ts` is for utility in testing. They can be extended in different ways in the future because the purposes are different.

For example `_util/assert.js` might have a feature to become noop in the production environment like assertion macros in other language. `testing/asserts.ts` might have richer messaging feature to better communicate when an error happened, which is unnecessary for `_util/assert.ts`

**Comment by kt3k** [comment] 2022-11-08 04:13
The difference of thrown error type is also meaningful. If you see `DenoStdInternalError`, then that's a bug of std. If you see `AssertionError`, it means something's wrong in your test cases.

**Comment by iuioiua** [comment] 2022-11-08 04:13
Both functions have been essentially identical since the inception of `_util/assert.ts`. They just use different error classes, which doesn't change how they operate in any meaningful way.

I'd still like to know, how come this rule isn't being applied to the other functions being used throughout the codebase from `testing/asserts.ts` such as `assertEquals`, `assertStringIncludes`, `fail`, `AssertionError`, `assertStrictEquals`, `assertNotStrictEquals`, `assertNotEquals` and `unreachable`?

And sorry for the overdrawn bikeshedding conversation for such a small function. This wasn't my initial intention 😅

**Comment by iuioiua** [comment] 2022-11-08 04:14
> The difference of thrown error type is also meaningful. If you see `DenoStdInternalError`, then that's a bug of std. If you see `AssertionError`, it means something's wrong in your test cases.

Ok, well said.

**Comment by iuioiua** [comment] 2022-11-08 07:40
> I'd still like to know, how come this rule isn't being applied to the other functions being used throughout the codebase from `testing/asserts.ts` such as `assertEquals`, `assertStringIncludes`, `fail`, `AssertionError`, `assertStrictEquals`, `assertNotStrictEquals`, `assertNotEquals` and `unreachable`?

If separation of concerns is so important, perhaps we can be more thorough. I suggest:
1. We create an internal version of each assertion that uses `DenoStdInternalError` and put it in `_util/asserts.ts`.
2. We create a tool that enforces use of `_util/asserts.ts` using `deno_graph`.

I'd be happy to do this.

**Comment by kt3k** [comment] 2022-11-08 10:15
> We create an internal version of each assertion that uses DenoStdInternalError and put it in _util/asserts.ts.

I don't think it's worth it because we probably only need `assert` for internal assertions (and the usages are not so much increasing). Maybe let's add others when they are needed.

> We create a tool that enforces use of _util/asserts.ts using deno_graph.

I think this would be useful.

**Comment by iuioiua** [comment] 2022-11-08 10:38
> Maybe let's add others when they are needed.

Sorry, I should've been clearer. That's what I was thinking - only assertions that are needed.

**Comment by iuioiua** [comment] 2022-11-08 10:42
It'd be good to hear from some thoughts from other maintainers too.

**Closed** 2022-11-14 07:33 UTC
