### ISSUE TITLE
assertSnapshot fails to match carriage return

### ISSUE THREAD

**Issue by OzzieOrca** [denoland/deno_std#4226] opened 2024-01-21 03:06 UTC
**Describe the bug**
If you pass the CR character `\r` to `assertSnapshot`, it saves the snapshot fine but then immediately fails to match the snapshot.

I ran into this by trying to snapshot the output of `stringify(...)` from `https://deno.land/std@0.212.0/csv/mod.ts` which apparently output CRLFs (`\r\n`).

**Steps to Reproduce**

1. Create a file (`crlf.test.ts`) with the contents
    ```ts
    import { assertSnapshot } from 'https://deno.land/std@0.212.0/testing/snapshot.ts';
    
    Deno.test('CR failure', async (t) => {
      await assertSnapshot(t, '\r');
    });
   ```
2. Run `deno test --allow-read --allow-write cr.test.ts -- --update` which returns
    ```
    running 1 test from ./cr.test.ts
    CR failure ... ok (2ms)
    ------- output -------
    
    > 1 snapshot updated.
    
    ok | 1 passed | 0 failed (4ms)
    ```
    and saves `__snapshots__/cr.test.ts.snap` with 
    ```ts
    export const snapshot = {};
    
    snapshot[`CR failure 1`] = `
    "
    "
    `;
    ```
3. Run `deno test --allow-read cr.test.ts` which returns:
    ```
    running 1 test from ./cr.test.ts
    CR failure ... FAILED (6ms)
    
     ERRORS 
    
    CR failure => ./cr.test.ts:3:6
    error: AssertionError: Snapshot does not match:
    
    
        [Diff] Actual / Expected
    
    
    -   "
    +   "
        "
    
        throw new AssertionError(
              ^
        at assertSnapshot (https://deno.land/std@0.212.0/testing/snapshot.ts:591:11)
        at async file:///home/scotty/code/Toptal/FoodNoms/macrosai-supabase/cr.test.ts:4:3
    
     FAILURES 
    
    CR failure => ./cr.test.ts:3:6
    
    FAILED | 0 passed | 1 failed (8ms)
    
    error: Test failed
    ```

**Expected behavior**

The test should succeed after the snapshot has been updated.

**Environment**

- OS: Ubuntu 22.04.3 LTS
- deno version: 1.39.1
- std version: 0.212.0

**Comment by javihernant** [comment] 2024-02-23 09:35
I'm taking a look at this one

**Comment by javihernant** [comment] 2024-02-23 12:40
The culprit seems to be [here](https://github.com/denoland/deno_std/blob/513805661bcbc56b7b6e84eca7bb83a450ab5fc0/testing/snapshot.ts#L394). When `.ts.snap` is written, an actual "\r" is written to the file. However, when `import`ing it reads a "\n". `import` bugs have to be fixed in the actual runtime (not in deno_std), right?

**Comment by kt3k** [comment] 2024-02-24 13:21
@javihernant Interesting finding! Can you create an issue in denoland/deno with a minimal repro example?

**Comment by kt3k** [comment] 2024-03-16 22:47
hmm looks like Deno ignoring `\r` in string literal is not a bug. Maybe we should escape `\r` when serializing it

**Comment by OzzieOrca** [comment] 2024-06-12 17:27
Sounds like `assertSnapshot` should strip (or escape somehow?) `\r` characters before comparing and storing snapshots. At least that's my takeaway from  https://github.com/denoland/deno/issues/22575#issuecomment-2162989848.

**Closed** 2024-07-08 10:33 UTC
Labels: bug, testing, PR welcome
