### ISSUE TITLE
flaky test failure on macOS with the error message `error: second time provided was later than self`

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#4473] opened 2024-03-11 14:18 UTC
ref: https://github.com/denoland/deno_std/actions/runs/8232991752/job/22511555909?pr=4471

```
error: second time provided was later than self

Stack backtrace:
   0: std::backtrace::Backtrace::capture
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: deno::tools::test::run_tests_for_worker::{{closure}}
   3: <deno_unsync::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   4: tokio::runtime::task::raw::poll
   5: tokio::runtime::runtime::Runtime::block_on
   6: tokio::runtime::task::raw::poll
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: std::sys::unix::thread::Thread::new::thread_start
  10: __pthread_start
```

**Comment by iuioiua** [comment] 2024-03-12 00:14
The error message gives almost no detail as to what failed. All the tests passed. However, 24 fewer tests pass than a [CI run that passes](https://github.com/denoland/deno_std/actions/runs/8232991752/job/22515993964?pr=4471). By comparing the test outputs of both failed and passing runs, the tests that aren't run in the failing run, in alphabetical order, are:

1. `./crypto/crypto_test.ts => digest() checks BLAKE2B vectors ...`
2. `./crypto/crypto_test.ts => digest() checks BLAKE2B-384 vectors ...`
3. `./crypto/crypto_test.ts => digest() checks BLAKE2S vectors ...`
4. `./crypto/crypto_test.ts => digest() checks BLAKE3 vectors ...`
5. `./crypto/crypto_test.ts => digest() checks KECCAK-224 vectors ...`
6. `./crypto/crypto_test.ts => digest() checks KECCAK-256 vectors ...`
7. `./crypto/crypto_test.ts => digest() checks KECCAK-384 vectors ...`
8. `./crypto/crypto_test.ts => digest() checks KECCAK-512 vectors ...`
9. `./crypto/crypto_test.ts => digest() checks MD4 vectors ...`
10. `./crypto/crypto_test.ts => digest() checks MD5 vectors ...`
11. `./crypto/crypto_test.ts => digest() checks RIPEMD-160 vectors ...`
12. `./crypto/crypto_test.ts => digest() checks SHA-1 vectors ...`
13. `./crypto/crypto_test.ts => digest() checks SHA-224 vectors ...`
14. `./crypto/crypto_test.ts => digest() checks SHA-256 vectors ...`
15. `./crypto/crypto_test.ts => digest() checks SHA-384 vectors ...`
16. `./crypto/crypto_test.ts => digest() checks SHA-512 vectors ...`
17. `./crypto/crypto_test.ts => digest() checks SHA3-224 vectors ...`
18. `./crypto/crypto_test.ts => digest() checks SHA3-256 vectors ...`
19. `./crypto/crypto_test.ts => digest() checks SHA3-384 vectors ...`
20. `./crypto/crypto_test.ts => digest() checks SHA3-512 vectors ...`
21. `./crypto/crypto_test.ts => digest() checks SHAKE128 vectors ...`
22. `./crypto/crypto_test.ts => digest() checks SHAKE256 vectors ...`
23. `./crypto/crypto_test.ts => digest() checks TIGER vectors ...`
24. `./crypto/crypto_test.ts => getRandomValues() passes through to native implementation ...`

The tests for these algorithms are started asynchronously [here](https://github.com/denoland/deno_std/blob/d63e97c735b6f3285099ceea73c5588b8dc1b6d8/crypto/crypto_test.ts#L1280), with the order given [here](https://github.com/denoland/deno_std/blob/d63e97c735b6f3285099ceea73c5588b8dc1b6d8/crypto/_wasm/mod.ts#L15).

So, considering the order in which the tests are run and the error given, I think what happens is that these algorithm tests start, and then the runtime momentarily chokes due to the high number of asynchronous operations.

I'm not sure if this means anything, but ignoring the `getRandomValues()` test, the tests for the crypto algorithms that do pass are `BLAKE2B-128`, `BLAKE2B-160`, `BLAKE2B-224` and `BLAKE2B-256`. I'm not sure it's worth suspecting the `blake2` crate being the cause.

**Comment by iuioiua** [comment] 2024-03-12 00:32
CC @mmastrac

**Comment by mmastrac** [comment] 2024-03-12 00:37
This one probably happened during the DST change. :)

The tests here use SystemTime:

```
        let elapsed = SystemTime::now().duration_since(earlier)?.as_millis();
```

**Comment by mmastrac** [comment] 2024-03-12 00:43
I think this will be fixed by https://github.com/denoland/deno/pull/22853

**Closed** 2024-03-12 01:30 UTC
