### ISSUE TITLE
Unified readme structures

### ISSUE THREAD

**Issue by timreichen** [denoland/deno_std#904] opened 2020-08-29 14:49 UTC
The readme files for `std` modules do not have a unified structure. Different header sizes for sections, some include API descriptions, some modules have no readme at all, some descriptions of submodules are missing. API descriptions are done n different styles (function/method lists, only examples, text descriptions etc.)

Would it be reasonable to define a structure that works for all `std` modules and then adjust the readme files according to that?

## varying doc styles
- [ ] bytes
- [ ] datetime
- [ ] encoding
- [ ] flags
- [ ] fs
- [ ] hash
- [ ] log
- [ ] node
- [ ] testing
- [ ] wasi
- [ ] ws

## incomplete
- [ ] archive
- [ ] fmt (#7172)
- [ ] http
- [ ] io (#7267)
- [ ] path
- [ ] uuid
## Missing
- [ ] async
- [ ] mime
- [ ] permissions
- [ ] signal
- [ ] textproto  (#7267)

## Possible relocation
- [ ] examples (#7278)

**Comment by bartlomieju** [comment] 2021-11-10 11:22
I'm not sure this issue is actionable. If we don't have an automatic way to enforce unified structure and formatting there will always be a drift. If anyone has proposed solution to the problem I'm glad to discuss them, but I'm leaning towards closing this issue.

**Comment by waldyrious** [comment] 2021-11-10 17:59
There's [standard-readme-preset](https://github.com/RichardLitt/standard-readme-preset), which can be used with [remark](https://github.com/remarkjs/remark) to enforce a common structure in README files, based in the [standard-readme spec](https://github.com/RichardLitt/standard-readme/blob/master/spec.md). Among the [rules it supports](https://github.com/RichardLitt/standard-readme-preset#rules), the following seem like they'd be useful for the purposes of this issue:

> * [`standard-readme:no-unknown-sections`](https://github.com/RichardLitt/standard-readme-preset/blob/master/rules/no-unknown-sections.js) — Check that only known sections are used, except for in the extra sections
> * [`standard-readme:require-sections`](https://github.com/RichardLitt/standard-readme-preset/blob/master/rules/require-sections.js) — Check that required sections (`contributing`, `license`) exist.
> `table-of-contents` is required if `toc: true` is given, optional for `toc: false`, and otherwise inferred based on if the number of lines in the file, excluding the ToC itself, exceeds 100.
> `install` and `usage` are required if `installable: true` is given.
> * [`standard-readme:section-order`](https://github.com/RichardLitt/standard-readme-preset/blob/master/rules/section-order.js) — Check that sections are used in the order they’re supposed to

I'm not sure how mature/stable it is, but it may be worth a try :)

**Comment by bartlomieju** [comment] 2021-11-10 18:02
@waldyrious if you want to try get it working on the repo I'll be more than happy to assist. That said, the project doesn't look too mature and has a very low star count so I'm a bit wary as having it as a dependency. Maybe we could get away with some custom made script that does the same?

**Comment by waldyrious** [comment] 2021-11-10 18:18
Looking at the code of `standard-readme-preset`, it does seem like a custom remark preset might be doable, yeah. That said, I've never worked with the preset before (or `remark`, for that matter), so I'm not sure how long it may take me to come up with something usable. I'll try to carve up some time to explore this sometime soon (possibly within the next few weeks).

**Comment by bartlomieju** [comment] 2021-11-10 22:18
@waldyrious cool! But no pressure, if it's too much work we can revisit the topic in the future.

**Comment by MierenManz** [comment] 2021-11-10 22:35
If there is a structure defined for this already then I don't mind adding a few pr's myself

**Comment by bartlomieju** [comment] 2021-11-10 22:36
> If there is a structure defined for this already then I don't mind adding a few pr's myself

@MierenManz the problem is we have no way to enforce this structure, so if someone misses discrepancy in the review the structure will not be preserved. That's why I suggested we should have an automated way of enforcing it before we do.

**Comment by timreichen** [comment] 2021-11-15 12:10
I agree an automated readme generation seems like the way to go.

**Comment by LionC** [comment] 2021-11-15 12:45
Is that actually something we need to lint? My impression is not that they are not unified because reviewers have missed to check against an agreed standard, but because there was no agreed standard.

I think it is more important to have an agreed standard, make sure that the current REAMEs and the contribution guide reflect that, so that the places new contributors will check put them on the right path and trust in the review process to catch hard deviations.

That said, my proposal for unification would be to reduce the "common structure" to:

- Starting with a top level heading followed by a **short** description of what the module does
- A link to the API documentation on `doc.deno.land` right underneath that, as that is often what users are actually searching for
- A table of contents
- An arbitrary amount of headings with an arbitrary number of sub levels and content following the heading structure in the ToC
- As a guideline and if applicable to the module, the first section should be a simple minimal working example, as that is often enough to get people started for simple use cases

**Comment by kt3k** [comment] 2022-11-25 11:47
Now the registry has the ability to show the JSDocs of APIs in a nice & organized way (See https://deno.land/std@0.166.0?doc for example), and therefore we've decided to document APIs only in JSDocs (ref https://github.com/denoland/deno_std/pull/2658).

Thank you for the suggestions and discussions anyway

**Closed by kt3k** 2022-11-25 11:47 UTC
Labels: help wanted, suggestion, needs investigation, ci
