### ISSUE TITLE
`it.ignore` and friends not type checking correctly when consumed from jsr.io

### ISSUE THREAD

**Issue by cowboyd** [denoland/deno_std#4611] opened 2024-04-19 13:34 UTC
**Describe the bug**

test flow control methods like `.ignore()`, `.skip()`, `.only()` and friends are not recognized as being part of the `it()` function when it is consumed from the `jsr:@std/testing@0.223.0/bdd` module.

It works as expected when consuming from https://deno.land/std@0.223.0/testing/bdd.ts

**Steps to Reproduce**

1. Create a file `ignore.test.ts` with the following contents:

```ts
import { describe, it } from "jsr:@std/testing@0.223.0/bdd";

describe("bdd", () => {
  it.ignore("can ignore a test case", () => {});
});
```

2. run the command:

```
$ deno test ignore.test.ts
```

You receive a type-checking error

```
Check ignore.test.ts
error: TS2339 [ERROR]: Property 'ignore' does not exist on type '<T>(...args: ItArgs<T>) => void'.
  it.ignore("can ignore a test case", () => {});
     ~~~~~~
    at ignore.test.ts:5:6
```

**Expected behavior**

It should type check correctly and run the test, producing: 

```
running 1 test from ./ignore.test.ts
bdd ...
  can ignore a test case ... ignored (0ms)
bdd ... ok (0ms)

ok | 1 passed | 0 failed | 0 ignored (1 step) (1ms)
```

The equivalent script that consumes the `bdd` module from https://deno.land works as expected. Here it is for comparison:

```ts
import { describe, it } from "https://deno.land/std@0.223.0/testing/bdd.ts";

describe("bdd", () => {
  it.ignore("can ignore a test case", () => {});
});
```

**Environment**

```
% deno --version
deno 1.42.4 (release, aarch64-apple-darwin)
v8 12.3.219.9
typescript 5.4.3
```

**Comment by andrewthauer** [comment] 2024-04-19 22:26
Duplicate of #23276

**Comment by kt3k** [comment] 2024-04-22 07:16
Please track at https://github.com/denoland/deno/issues/23276

**Closed by kt3k** 2024-04-22 07:16 UTC
Labels: bug, needs triage
