### ISSUE TITLE
TS2345 [ERROR]: Argument of type 'string | RegExpExecArray' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1916] opened 2022-02-14 00:44 UTC
**Describe the bug**
TS2345 [ERROR]: Argument of type 'string | RegExpExecArray' is not assignable to parameter of type 'string'.
  Type 'RegExpExecArray' is not assignable to type 'string'.
      (slashes || (proto && !slashedProtocol.has(proto)))
                                                 ~~~~~
    at https://deno.land/std@0.125.0/node/url.ts:687:50

**Steps to Reproduce**

<!--
Example
1. Create a file with the contents ...
2. Create a script with the contents ...
3. Execute the command ...
4. See error
-->

**Expected behavior**

<!-- A clear and concise description of what you expected to happen. -->

**Environment**

<!-- please complete the following information -->

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by lucacasonato** [comment] 2022-02-14 09:57
Duplicate of #1868. `std` does not support TypeScript "loose" mode.

**Closed by lucacasonato** 2022-02-14 09:57 UTC
Labels: bug, needs triage
