### ISSUE TITLE
`getUid` not on type `typeof Deno`

### ISSUE THREAD

**Issue by WilliamRagstad** [denoland/deno_std#1945] opened 2022-02-21 19:53 UTC
I'm building a website using the framework Aleph.js and for some reason I'm getting the following error:
```css
error: Uncaught (in promise) TypeError: TS2339 [ERROR]: Property 'getUid' does not exist on type 'typeof Deno'.
    if (Deno.build.os !== "windows" && info.uid === Deno.getUid()) {
...
```
It appears that the error is thrown inside an await expression used by this code:
```ts
async function importPostcssPluginByName(name: string) {
  const url = `https://esm.sh/${name}?deps=postcss@${postcssVersion}&bundle&no-check`
  const { default: Plugin } = await import(url) // <-- Here
  return Plugin
}
```
https://github.com/denoland/deno_std/blob/3b43d075ea6977e10bb1d9bd58fbeacc721a114e/node/_fs/_fs_access.ts#L24

Does anyone know what could have caused this? From https://github.com/denoland/deno/issues/13493 and https://github.com/denoland/deno/pull/13496 it seems to be perfectly valid.

**Comment by crowlKats** [comment] 2022-02-21 19:54
Duplicate of https://github.com/denoland/deno_std/issues/1927

**Closed by crowlKats** 2022-02-21 19:54 UTC
