### ISSUE TITLE
TS2322 [ERROR]: Type 'number | Partial<NetConnectOptions>' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1909] opened 2022-02-13 14:09 UTC
**Describe the bug**
TS2322 [ERROR]: Type 'number | Partial<NetConnectOptions>' is not assignable to type 'number'.
  Type 'Partial<TcpNetConnectOptions>' is not assignable to type 'number'.
    (options as TcpSocketConnectOptions).port = arg0;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/node/net.ts:287:5

**Steps to Reproduce**
1. Create a file with the contents ...
2. Create a script with the contents ...
3. Execute the command ...
4. See error

**Expected behavior**
No error reporting.
<!-- A clear and concise description of what you expected to happen. -->

**Environment**

<!-- please complete the following information -->

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by djedr** [comment] 2022-02-13 17:00
Reason for this is that type inference fails because the `arg === null` case is not handled.

This can be solved by replacing line 280 with:

```js
  if (arg0 !== null) if (typeof arg0 === "object") {
```

(+ wrap the enclosing `if`s body in curlies for proper style)

although whether that makes sense for the rest of the logic is another question (`options` will then remain empty).

**Comment by idanran** [comment] 2022-02-13 17:08
> Reason for this is that type inference fails because the `arg === null` case is not handled.
> 
> This can be solved by replacing line 280 with:
> 
> ```js
>   if (arg0 !== null) if (typeof arg0 === "object") {
> ```
> 
> (+ wrap the enclosing `if`s body in curlies for proper style)
> 
> although whether that makes sense for the rest of the logic is another question (`options` will then remain empty).

Maybe you can try to mention pr. I don't know much about typescript.

**Comment by kt3k** [comment] 2022-02-14 04:05
> Create a file with the contents ...
> Create a script with the contents ...

What is the 'contents' here?

I don't see a type error when I run the command `deno run --unstable https://deno.land/std@0.122.0/node/net.ts`. Do you have some customized compiler options?

**Comment by idanran** [comment] 2022-02-14 04:10
> > Create a file with the contents ...
> > Create a script with the contents ...
> 
> What is the 'contents' here?
> 
> I don't see a type error when I run the command `deno run --unstable https://deno.land/std@0.122.0/node/net.ts`. Do you have some customized compiler options?

I turned off strict mode in Typescript.

**Comment by kitsonk** [comment] 2022-02-14 04:12
Duplicate of #1868

`std` does not work under "loose" mode in TypeScript and we shouldn't make it.  When you turn off strict mode, you disable a lot of CFA which is a "bad" thing.

**Comment by idanran** [comment] 2022-02-14 04:15
> Duplicate of #1868
> 
> `std` does not work under "loose" mode in TypeScript and we shouldn't make it. When you turn off strict mode, you disable a lot of CFA which is a "bad" thing.

The purpose is to enable fast code migration. From Node to Deno.

**Comment by idanran** [comment] 2022-02-14 04:16
> Duplicate of #1868
> 
> `std` does not work under "loose" mode in TypeScript and we shouldn't make it. When you turn off strict mode, you disable a lot of CFA which is a "bad" thing.

I admit, it's really not a very good solution.

**Comment by kitsonk** [comment] 2022-02-14 04:22
@idanran then `--no-check=remote` is likely the solution you are looking for.

**Comment by idanran** [comment] 2022-02-14 04:25
> @idanran then `--no-check=remote` is likely the solution you are looking for.

Thank you.

**Comment by lucacasonato** [comment] 2022-02-14 09:55
Duplicate of #1868. `std` does not support TypeScript "loose" mode.

**Closed by lucacasonato** 2022-02-14 09:55 UTC
Labels: bug, needs triage
