### ISSUE TITLE
node/global.ts doesn't polyfill during importing module

### ISSUE THREAD

**Issue by hirochachacha** [denoland/deno_std#2068] opened 2022-03-27 06:04 UTC
**Describe the bug**

**Steps to Reproduce**

main.ts
```typescript
import "https://deno.land/std@0.132.0/node/global.ts";
import "./mod.ts";
```

mod.ts
```typescript
console.log(Buffer);
```

then

```
$ deno run --allow-all main.ts
```

got

```
Check file:///xxx/main.ts
error: Uncaught ReferenceError: Buffer is not defined
console.log(Buffer);
            ^
    at file:///xxx/mod.ts:1:13
```

**Expected behavior**

no errors

**Environment**

- OS: MacOS 12.3
- deno version: 1.19.3
- std version: 0.132.0

FWIW, this issue has been persisted since 702914453d59a37591004319d329fbd5bf6beb86, std@0.110.0 works fine as far as I know.
Although I'm not sure where the root cause comes from. It could be a runtime or compiler issue.

**Comment by hirochachacha** [comment] 2022-03-27 06:11
Another work-around is using dynamic import: `import("./mod.ts")`, which I'm currently using.

**Comment by lino-levan** [comment] 2022-11-05 05:49
This seems to have been fixed when https://github.com/denoland/deno_std/pull/2098 was merged. This has not been reproducable since std@0.134.0 (all later versions work as expected).

This issue should be closed.

**Comment by cjihrig** [comment] 2022-11-05 14:34
Thanks, I'll close this out then.

**Closed by cjihrig** 2022-11-05 14:34 UTC
Labels: bug
