### ISSUE TITLE
TS2322 [ERROR]: Type 'string | Error' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by idanran** [denoland/deno_std#1912] opened 2022-02-14 00:35 UTC
**Describe the bug**
TS2322 [ERROR]: Type 'string | Error' is not assignable to type 'string'.
  Type 'Error' is not assignable to type 'string'.
      message: message ?? "Failed",
      ~~~~~~~
    at https://deno.land/std@0.125.0/node/assert.ts:368:7

    The expected type comes from property 'message' which is declared here on type 'ExtendedAssertionErrorConstructorOptions'
      message?: string;
      ~~~~~~~
        at https://deno.land/std@0.125.0/node/assertion_error.ts:361:3

**Steps to Reproduce**

**Expected behavior**

**Environment**

- OS: Windows11
- deno version: 1.18.2
- std version: 0.125.0

**Comment by lucacasonato** [comment] 2022-02-14 09:56
Duplicate of #1868. `std` does not support TypeScript "loose" mode.

**Closed by lucacasonato** 2022-02-14 09:56 UTC
Labels: bug, needs triage
