### ISSUE TITLE
dayOfYear test fails on my machine

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#3659] opened 2023-09-19 18:59 UTC
```
[std/datetime] dayOfYear => ./datetime/day_of_year_test.ts:189:6
error: AssertionError: Values are not equal.


    [Diff] Actual / Expected


-   73
+   74

  throw new AssertionError(message);
        ^
    at assertEquals (file:///V:/deno_std/assert/assert_equals.ts:53:9)
    at fn (file:///V:/deno_std/datetime/day_of_year_test.ts:201:5)
```

**Comment by lino-levan** [comment] 2023-09-20 06:30
Related / duplicate of #3571

**Closed** 2023-09-25 15:16 UTC
Labels: duplicate, needs triage
