### ISSUE TITLE
`io.readLines` yield incomplete lines

### ISSUE THREAD

**Issue by lambdalisue** [denoland/deno_std#1150] opened 2021-08-22 17:18 UTC
**Describe the bug**

It seems `io.readLines` yield incomplete lines in some cases.

**To Reproduce**

Add `gen.ts` as

```typescript
import { parse } from "https://deno.land/std@0.105.0/flags/mod.ts";

const opts = parse(Deno.args)
const size = opts.size || 128;
const v = "x".repeat(1024 * size);
const b = new TextEncoder().encode(`["${v}"]`);

await Deno.stdout.write(b);
console.log("");
```

And add `test.ts` as

```typescript
import * as io from "https://deno.land/std@0.100.0/io/mod.ts";

for await (const line of io.readLines(Deno.stdin)) {
  console.log(`Recv ${line.length}`);
  if (!line) {
    continue;
  }
  JSON.parse(line);
}
```

When the buffer size is small enough, it process successfully.

```
deno run gen.ts --size=1 | deno run test.ts
Check file:///Users/alisue/ghq/github.com/lambdalisue/deno-io-test/gen.ts
Check file:///Users/alisue/ghq/github.com/lambdalisue/deno-io-test/test.ts
Recv 1028
Recv 0
```

But when the buffer size is big, `io.readLines` yield incomplete lines like

```
deno run gen.ts --size=100 | deno run test.ts
Check file:///Users/alisue/ghq/github.com/lambdalisue/deno-io-test/gen.ts
Check file:///Users/alisue/ghq/github.com/lambdalisue/deno-io-test/test.ts
Recv 16384
error: Uncaught (in promise) SyntaxError: Unexpected end of JSON input
  JSON.parse(line);
       ^
    at JSON.parse (<anonymous>)
    at file:///Users/alisue/ghq/github.com/lambdalisue/deno-io-test/test.ts:8:8
```

**Expected behavior**

`io.readLines` waits for a complete line.

**Desktop (please complete the following information):**

- OS: macOS 11.5
- Version

```
deno 1.13.0 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```

**Additional context** 
https://github.com/lambdalisue/deno-io-test

**Comment by bartlomieju** [comment] 2021-08-22 18:13
That's caused by:
```ts
await Deno.stdout.write(b);
console.log("");
```

`write()` is a single syscall and it can write up to about 16Kb of data at once (with matches your `Recv` value). Use [`writeAll`](https://deno.land/std@0.105.0/io/util.ts#L170) instead and the problem will go away.

**Comment by mattn** [comment] 2021-08-22 18:20
No, If the write side writes large data using buffer with some times, readLines won't handle correctly.

**Comment by bartlomieju** [comment] 2021-08-22 18:27
> No, If the write side writes large data using buffer with some times, readLines won't handle correctly.

Please provide reproduction for this scenario

**Comment by lambdalisue** [comment] 2021-08-23 01:17
> write() is a single syscall and it can write up to about 16Kb of data at once (with matches your Recv value). Use writeAll instead and the problem will go away.

Oops. I've forgotten about why there is the `writeAll` function... As you said, I could not find any issue with the following `gen.ts`

```typescript
import { parse } from "https://deno.land/std@0.105.0/flags/mod.ts";
import * as io from "https://deno.land/std@0.100.0/io/mod.ts";

const opts = parse(Deno.args)
const size = opts.size || 128;
const v = "x".repeat(1024 * size);
const b = new TextEncoder().encode(`["${v}"]`);

await io.writeAll(Deno.stdout, b);
console.log("");
```

It can handle `1024 * 1024` data, so it seems it's no longer an issue for me. Let wait for what @mattn can provide...

**Comment by mattn** [comment] 2021-08-23 02:37
Sorry, I was cofused. This is not a cause of deno. Please close this,

**Closed** 2021-08-23 07:27 UTC
Labels: bug, needs triage
