### ISSUE TITLE
 Top-level await promise never resolved

### ISSUE THREAD

**Issue by dong-lufei** [denoland/deno_std#3144] opened 2023-01-28 09:47 UTC
https://deno.land/manual@v1.30.0/examples/os_signals

According to your documentation, I run and report an error
```
import { signal } from "https://deno.land/std@0.174.0/signal/mod.ts";
// Windows 只支持 SIGINT 和 SIGBREAK
const sig = signal("SIGBREAK", "SIGINT");

// Add a timeout to prevent process exiting immediately.
setTimeout(() => {}, 5000);

for await (const _ of sig) {
  console.log("顶级等待承诺从未解决");
}
```
error: Top-level await promise never resolved
for await (const _ of sig) {
                 ^
    at <anonymous> (file:///E:/test/deno/deno01/index.ts:667:18)

**Comment by lino-levan** [comment] 2023-01-28 15:46
What version of Deno are you using? What command are you using to run this code snippet? The documentation example works fine on my Mac (running Deno `1.30.0`)

**Comment by GJZwiers** [comment] 2023-01-29 18:23
I believe this is not a bug but the expected behavior in this case. I made an issue for the same thing a while back (note that the error message was different then): https://github.com/denoland/deno_std/issues/1941#issuecomment-1061293369

**Comment by dong-lufei** [comment] 2023-01-30 05:18
```
# 13697 @ donglufei in E:\test\deno\deno01 [12:50:00]
$ deno run -A index.js
error: Top-level await promise never resolved
for await (const _ of sig) {
                 ^
    at <anonymous> (file:///E:/test/deno/deno01/index.js:146:18)

# 13697 @ donglufei in E:\test\deno\deno01 [13:17:36] C:1
$ deno -v
error: Found argument '-v' which wasn't expected, or isn't valid in this context

        If you tried to supply `-v` as a value rather than a flag, use `-- -v`

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help


# 13697 @ donglufei in E:\test\deno\deno01 [13:17:41] C:1
$ deno -V
deno 1.30.0

# 13697 @ donglufei in E:\test\deno\deno01 [13:17:45]
$

```

**Comment by iuioiua** [comment] 2024-04-16 04:29
Closing this as `std/signals` was deprecated and removed from the Standard Library a while ago. Please take a look at the [OS Signals documentation](https://docs.deno.com/runtime/tutorials/os_signals). If the code there doesn't work for your use case, please open a ticket in https://github.com/denoland/deno-docs.

**Closed by iuioiua** 2024-04-16 04:29 UTC
