### ISSUE TITLE
Assert diff swaps actual and expected when comparing multiline strings

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno_std#3681] opened 2023-09-29 12:06 UTC
**Describe the bug**

When `assertEquals` is used to compare a multiline string and the check fails, then the diff output confusingly swaps the order of actual and expected.

<img width="402" alt="Screenshot 2023-09-29 at 14 05 02" src="https://github.com/denoland/deno_std/assets/1062408/a7f34385-bbce-4e7b-8c93-338435406b46">

**Steps to Reproduce**

```tsx
import { assertEquals } from "https://deno.land/std@0.203.0/assert/mod.ts";

Deno.test("multiline", () => {
  const actual = `<div>
  <div>
    <p>
    foo</p>
  </div>
  [object Object],barbaz</div>
</div>  
`;

  const expected = `<div>
  <div>
    <p>foo</p>
    barbaz
  </div>
</div>
`;
  assertEquals(actual, expected);
});
```

**Expected behavior**

It should not swap the order. It should mark actual as "actual" and expected as "expected".

**Environment**

- OS: [e.g. Ubuntu 20.04, MacOS 11]
- deno version: 1.37.1
- std version: 0.203.0

**Comment by marvinhagemeister** [comment] 2023-09-29 12:20
Might be related https://github.com/denoland/deno_std/issues/3039

**Comment by lucacasonato** [comment] 2023-10-02 04:28
Duplicate of #3039

**Comment by kt3k** [comment] 2023-10-03 11:31
It looks like this happens only when `actual` has more diff lines than `expected`. I'll look into more details.

```js
import { assertEquals } from "https://deno.land/std@0.203.0/assert/mod.ts";
Deno.test("multiline", () => {
  assertEquals("a\na", "e"); // diff swaps
});
Deno.test("multiline", () => {
  assertEquals("a\na", "e\ne"); // diff doesn't swap
});
Deno.test("multiline", () => {
  assertEquals("a", "e\ne"); // diff doesn't swap
});
```

**Closed** 2023-10-04 01:43 UTC
Labels: bug
