### ISSUE TITLE
node/timers/promises.ts is broken

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#1336] opened 2021-10-02 17:20 UTC
```js
// test.js
import { setTimeout } from "https://deno.land/std/node/timers/promises.ts";

const res = await setTimeout(100, 'result');

console.log(res);  // Prints 'result'
```

```
$ deno run test.js
error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promise.

```

**Comment by kt3k** [comment] 2021-10-06 07:02
I think we need to follow the node.js implementation https://github.com/nodejs/node/blob/28f711b5521f5e2949405c620a6e0e1a3cadd7c6/lib/timers/promises.js

Current usage of promisify to timer functions looks wrong to me

**Comment by bartlomieju** [comment] 2021-10-06 17:03
> I think we need to follow the node.js implementation https://github.com/nodejs/node/blob/28f711b5521f5e2949405c620a6e0e1a3cadd7c6/lib/timers/promises.js
> 
> Current usage of promisify to timer functions looks wrong to me

I agree, `promisify` seemed fished in this use case.

**Comment by kasperk81** [comment] 2021-11-08 10:53
same error was reported here https://github.com/denoland/deno/issues/11469#issuecomment-963029366, but it was pinned on the consumer code. node.js jsc, d8 and browsers don't have problem with orphanded async calls. deno seems to be too sensitive. i am having a hard time root causing the issue in a large project with 100s of async requests in flight.

**Comment by lino-levan** [comment] 2022-11-05 17:57
It looks like this has since resolved itself. The error changed from
`error: Module evaluation is still pending but there are no pending ops or dynamic imports. This situation is often caused by unresolved promises.`
to
`error: Uncaught TypeError: Callback must be a function. Received 100`
in std 0.122.0

and from
`error: Uncaught TypeError: Callback must be a function. Received 100`
to no error (a printing of `result`) in std 0.139.0 onwards

I haven't had the time to find the specific merges that caused these changes but I believe this issue should be closed.

**Comment by kt3k** [comment] 2022-11-07 05:07
@lino-levan Thanks for checking various versions.

I think this PR has fixed the issue https://github.com/denoland/deno_std/pull/2198

Closing as fixed.

**Closed by kt3k** 2022-11-07 05:07 UTC
Labels: bug, node
