### ISSUE TITLE
type errors with `noUncheckedIndexedAccess`

### ISSUE THREAD

**Issue by DetachHead** [denoland/deno_std#1837] opened 2022-01-23 02:50 UTC
main.js:
```ts
export * as log from "https://deno.land/std@0.122.0/log/mod.ts";
```
deno.json:
```json
{
  "compilerOptions": {
    "noUncheckedIndexedAccess": true
  }
}
```
```
error: TS2339 [ERROR]: Property 'offset' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
      const { offset, start, end } = this.chunks[i];
              ~~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:76:15

TS2339 [ERROR]: Property 'start' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
      const { offset, start, end } = this.chunks[i];
                      ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:76:23

TS2339 [ERROR]: Property 'end' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
      const { offset, start, end } = this.chunks[i];
                             ~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:76:30

TS2339 [ERROR]: Property 'value' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
    const { value, offset, start } = this.chunks[idx];
            ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:96:13

TS2339 [ERROR]: Property 'offset' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
    const { value, offset, start } = this.chunks[idx];
                   ~~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:96:20

TS2339 [ERROR]: Property 'start' does not exist on type '{ value: Uint8Array; start: number; end: number; offset: number; } | undefined'.
    const { value, offset, start } = this.chunks[idx];
                           ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:96:28

TS2532 [ERROR]: Object is possibly 'undefined'.
    let firstOffset = start - first.offset;
                              ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:107:31

TS2532 [ERROR]: Object is possibly 'undefined'.
      for (let j = chunk.start + firstOffset; j < chunk.end; j++) {
                   ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:110:20

TS2532 [ERROR]: Object is possibly 'undefined'.
      for (let j = chunk.start + firstOffset; j < chunk.end; j++) {
                                                  ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:110:51

TS2532 [ERROR]: Object is possibly 'undefined'.
        yield chunk.value[j];
              ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:111:15

TS2322 [ERROR]: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
        yield chunk.value[j];
              ~~~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:111:15

TS2532 [ERROR]: Object is possibly 'undefined'.
      const len = chunk.end - chunk.start;
                  ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:131:19

TS2532 [ERROR]: Object is possibly 'undefined'.
      const len = chunk.end - chunk.start;
                              ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:131:31

TS2532 [ERROR]: Object is possibly 'undefined'.
      result.set(chunk.value.subarray(chunk.start, chunk.end), written);
                 ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:132:18

TS2532 [ERROR]: Object is possibly 'undefined'.
      result.set(chunk.value.subarray(chunk.start, chunk.end), written);
                                      ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:132:39

TS2532 [ERROR]: Object is possibly 'undefined'.
      result.set(chunk.value.subarray(chunk.start, chunk.end), written);
                                                   ~~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:132:52

TS2532 [ERROR]: Object is possibly 'undefined'.
    result.set(last.value.subarray(last.start, last.start + rest), written);
               ~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:137:16

TS2532 [ERROR]: Object is possibly 'undefined'.
    result.set(last.value.subarray(last.start, last.start + rest), written);
                                   ~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:137:36

TS2532 [ERROR]: Object is possibly 'undefined'.
    result.set(last.value.subarray(last.start, last.start + rest), written);
                                               ~~~~
    at https://deno.land/std@0.122.0/bytes/bytes_list.ts:137:48

TS2322 [ERROR]: Type 'number | undefined' is not assignable to type 'number | null'.
  Type 'undefined' is not assignable to type 'number | null'.
    return c;
    ~~~~~~~~~
    at https://deno.land/std@0.122.0/io/buffer.ts:450:5

TS2322 [ERROR]: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
      prefixEnd = lps[prefixEnd - 1];
      ~~~~~~~~~
    at https://deno.land/std@0.122.0/io/buffer.ts:922:7

TS2322 [ERROR]: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
          matchIndex = delimLPS[matchIndex - 1];
          ~~~~~~~~~~
    at https://deno.land/std@0.122.0/io/buffer.ts:975:11

TS2532 [ERROR]: Object is possibly 'undefined'.
    await handler.setup();
          ~~~~~~~
    at https://deno.land/std@0.122.0/log/mod.ts:184:11

TS2345 [ERROR]: Argument of type 'BaseHandler | undefined' is not assignable to parameter of type 'BaseHandler'.
  Type 'undefined' is not assignable to type 'BaseHandler'.
    state.handlers.set(handlerName, handler);
                                    ~~~~~~~
    at https://deno.land/std@0.122.0/log/mod.ts:185:37

TS2532 [ERROR]: Object is possibly 'undefined'.
    const handlerNames = loggerConfig.handlers || [];
                         ~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/log/mod.ts:195:26

TS2532 [ERROR]: Object is possibly 'undefined'.
    const levelName = loggerConfig.level || DEFAULT_LEVEL;
                      ~~~~~~~~~~~~
    at https://deno.land/std@0.122.0/log/mod.ts:205:23
```

**Comment by crowlKats** [comment] 2022-01-23 05:43
Duplicate of #937

**Closed by crowlKats** 2022-01-23 05:43 UTC
Labels: bug, needs triage
