### ISSUE TITLE
ProtocolError: malformed MIME header initial line

### ISSUE THREAD

**Issue by reggi** [denoland/deno_std#40] opened 2018-12-22 04:17 UTC
I'm sending over a `POST` request and I think it's confusing the body for the header.

`ProtocolError: malformed MIME header initial line:   "query": "{ hello }",`

**Comment by kevinkassimo** [comment] 2018-12-22 04:57
Could you post the raw response that triggers this error?

**Comment by reggi** [comment] 2018-12-22 05:11
```
{
  "query": "{ hello }",
  "operationName": "",
  "variables": {}
}
```

**Comment by kevinkassimo** [comment] 2018-12-22 06:36
Actually, have you sent the request correctly? Because it seems as if it is treating `"query": "{ hello }",` as the initial header line, which should only happen when it reads the first line `{` as the request line... (looks as if no request line nor headers are sent along with the body...)

**Comment by bartlomieju** [comment] 2018-12-27 17:13
I managed to reproduce this issue, and it turns out this problem arises if you try to respond to request without reading its body.

`http_bench.ts`
```ts
import * as deno from "deno";
import { serve } from "./http.ts";

const addr = deno.args[1] || "127.0.0.1:4500";
const server = serve(addr);

const body = new TextEncoder().encode("Hello World");

async function main(): Promise<void> {
  for await (const request of server) {
    await request.body() // adding this line prevent ProtocolError
    await request.respond({ status: 200, body });
  }
}

main();
``` 

I guess a check is needed in `request.respond` that ensures whole requests has been read.

**Comment by bartlomieju** [comment] 2019-05-20 09:41
I believe this was resolved in #49, can we close this now?

**Closed** 2019-05-20 14:22 UTC
