### ISSUE TITLE
Uncaught BrokenPipe: Broken pipe (os error 32)  

### ISSUE THREAD

**Issue by ITS-NIGHTOWL** [denoland/deno_std#659] opened 2020-06-16 17:44 UTC
After running my ws client for 11 hours, I got this error (for the first time):
```
error: Uncaught BrokenPipe: Broken pipe (os error 32)   
    at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
    at Object.sendAsyncMinimal ($deno$/ops/dispatch_minimal.ts:106:10)
    at async Object.write ($deno$/ops/io.ts:65:18)
    at async BufWriter.flush (https://deno.land/std@0.54.0/io/bufio.ts:479:25)
    at async writeFrame (https://deno.land/std@0.54.0/ws/mod.ts:144:3)
```
Any reasons as to why?

**Comment by lideming** [comment] 2021-02-12 12:53
@timonson 
> at async ServerRequest.respond (server.ts:84:7)

Do you use other library or call `ServerRequest.respond` directly? The caller have to catch and handle the error.

**Comment by timonson** [comment] 2021-02-12 16:59
Hi @lideming , thanks for coming back to this issue!

I call `ServerRequest.respond` directly. In fact, I just tried to reproduce this error with the following code and I was able to do it several times:

```typescript
import { serve } from "https://deno.land/std@0.86.0/http/server.ts";
const server = serve({ port: 8080 });
console.log("http://localhost:8080/");
for await (const req of server) {
  req.respond({ body: await Deno.readFile("./cat.jpeg") });
}
```

> error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async BufWriter.write (bufio.ts:499:29)
    at async writeResponse (_io.ts:273:15)
    at async ServerRequest.respond (server.ts:89:7)

The second most annoying thing is that even if I tried to catch the error, it would not work and the server breaks.

The most annoying thing is that it is not deterministically reproducible. 

But here is what has worked for me:

1. Open three different browsers (switching between browsers seems to be the key factor).
2. Refresh the browsers in no specific order.
3. Don't give up if it doesn't break immediately.

Please let me know if you are able to reproduce it. Otherwise I could make a video showing what is happening. But there is not really more magic to it than what I already explained.

**Comment by timonson** [comment] 2021-02-12 17:49
Thanks for coming back to this issue @lideming !

Although I still don't know what exactly causes this error, it looks like I made a mistake in my error handling function.
I caught the error on `req.respond({status: 200})` correctly, but what I forgot is adding a `catch` statement to `req.respond({status: 500})` inside my error handler function.

**Comment by lideming** [comment] 2021-02-12 18:25
@timonson The `BrokenPipe` error usually means trying to send data to a closed/broken connection.
For example, the user interrupts loading while the browser is receiving content from the server, then the browser stops receiving, closes the connection, and causes the `BrokenPipe` error on the server which was sending data.

**Comment by nuts-n-bits** [comment] 2021-02-26 03:30
For me this error tends to happen when I saturate the TCP connection, maybe some connection gets dropped by the os for whatever reason and now you're writing to a broken pipe. What makes it troubling is that this is uncatchable within the `for await` loop, from limited testing, it seems the way to catch it is this:
```ts
while(true) {
    try {
        for await (const request of server) {
            // serve the request
        }
    } 
    catch(e} {
         // handel error 
    }
}
```
The reason of which I'm sure can be made sense of by folks who understand how async iterators work better than I do, but I'm still confused by this lol.

**Comment by OverGlass** [comment] 2021-03-16 14:27
Same problem for me. Every 6 -12 hours of running.
On Ubuntu, behind nginx. - Deno 1.8.0
- static files server 
-  api over HTTP

How can I help for debugging this ? This is in production and I really want to dig into this.

**Comment by malimohub** [comment] 2021-03-16 16:26
Is there a fix coming out for this? Deno is pretty unusable at this point

**Comment by lucacasonato** [comment] 2021-03-16 16:34
@malimohub The error is that you are not catching the error... see https://github.com/denoland/deno_std/issues/659#issuecomment-786386671. It is totally expected for this error to happen (connections sometimes close unexpectedly). It might be more obvious what is happening if instead of using `for await`, you called `const req = await server.next()` in an infinite loop manually.

**Comment by matt1** [comment] 2021-03-20 21:24
For me this is still happening.

Scenario is browser making a HTTP `fetch` to the Deno server - this fetch can be slow and might need to be cancelled by the browser, so they do this via standard [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).  I.e. the browser explicitly aborts the connection - that is fine and I understand why this creates the broken pipe.  I just want to be able to catch this.

I have something like this and it *does not catch* the error, and causes the server to crash.

```javascript
import {serve, Server} from "https://deno.land/std/http/server.ts";

export class FooServer {
  readonly server:Server;

 constructor() {
   this.server.serve({port:8080});
 }

 async serve() {
   while (true) {
      try {
        for await (const request of this.server) {
          // ...
       }
     } catch (error) {
       // does not catch
     }
 }

}
```

```javascript
// elsewhere
const fooServer = new FooServer();
fooServer.serve();  // loops forever
```
Wrapping `fooServer.serve()` in a try-catch does not catch either.

This is the uncatchable error generated when browsers use `AbortController.abort()` that crashes the server:
```
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32) 
      throw new ErrorClass(res.err.message);
            ^
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
    at async write (deno:runtime/js/12_io.js:118:20)
    at async BufWriter.write (https://deno.land/std@0.90.0/io/bufio.ts:499:29)
    at async writeResponse (https://deno.land/std@0.90.0/http/_io.ts:274:15)
    at async ServerRequest.respond (https://deno.land/std@0.90.0/http/server.ts:88:7)
```

I do not understand the comment about `server.next()` - the compiler responds with `error: TS2339 [ERROR]: Property 'next' does not exist on type 'Server'.` - I can see that this is some sort of `AsyncIterator` and the interface appears to have a `next()` method, but the compiler rejects it anyway so I guess something is broken somewhere.

Please advise if there is some sort of online repl.it/stackblitz type place that would be appropriate to create a minimal reproduction.

**Comment by nuts-n-bits** [comment] 2021-03-21 14:40
> @malimohub The error is that you are not catching the error... see [#659 (comment)]

Well, I have a minor objection. Because all the docs and tutorials, official or not, was pretty much using the pattern `for await (req of server)` directly at the top level it makes me feel like that's how it's intended to be used, so I expect it to not throw at all. If the intention of `server` is to throw, then the docs should really mention `while true try catch` (or whatever) instead, so that everyone isn't surprised by the behaviour.  And I agree that some error deserves to be thrown, but without proper documentation, I was under the impression that all that can go wrong should go wrong during `request.respond()`

So anyways maybe update the docs to reflect this? On the other hand, `while true try catch` at top level is really ugly lol

**Comment by KotadiyaHiral** [comment] 2021-03-26 06:23
```
0|app      |     at async Collection.findOne (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/collection/collection.ts:43:12)
0|app      | 2021-03-26T06:15:07.234Z [10] BrokenPipe: Broken pipe (os error 32) 
0|app      |     at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:60:13)
0|app      |     at sendAsync (deno:runtime/js/10_dispatch_minimal.js:99:12)
0|app      |     at async write (deno:runtime/js/12_io.js:118:20)
0|app      |     at async Object.writeAll (deno:runtime/js/13_buffer.js:224:19)
0|app      |     at async WireProtocol.command (https://raw.githubusercontent.com/manyuanrong/deno_mongo/refactor/src/protocol/protocol.ts:55:7)
```

In my case, broken pipe error generated from deno_mongo.

**Comment by zigomir** [comment] 2021-04-15 18:54
I was also getting this error using `http/serve`. I now tried new unstable http api as described in [Deno 1.9 blog post](https://deno.com/blog/v1.9#native-http%2F2-web-server) and couldn't reproduce the problem (yet) 🕶.

**Comment by MrOggy85** [comment] 2021-05-25 15:19
I also switch to the new api, but got the same error as mentioned previously in this issue.
However, I was not using `await` with `respondWith`. When I added `await` I successfully caught the error and the execution could continue.

```ts
await respondWith(
  new Response(body, {
    headers,
    status: 200,
  }),
);
```

I made the same mistake with the previous api, by not prefixing `request.respond` with `await`.

**Comment by bartlomieju** [comment] 2021-11-09 17:04
`std/http` and `std/ws` implementations were rewritten to leverage native HTTP bindings available in Deno (`Deno.serveHttp`). This error should no longer occur. I'm going to tentatively close this issue, please let me know if the problem persists.

**Closed by bartlomieju** 2021-11-09 17:04 UTC
Labels: bug

**Comment by ralyodio** [comment] 2021-11-18 12:04
does this impact oak?

I'm runngin puppeteer and if I do 5 instances at a time it crashes.

**Comment by bartlomieju** [comment] 2021-11-18 12:14
`oak` doesn't use `std/http` anymore in the latest version so it shouldn't be affected.

**Comment by Jekahome** [comment] 2021-12-16 21:50
I get this error when I intensively fill with data of 64 kb 3000 iterations
```rust
let size_byte = 65535; 
                let buff = (0..=size_byte).map(|_|78).collect::<Vec<u8>>();
                
                addr.do_send(ClientCommand( Item::FirstBinary( Bytes::from_iter(buff.clone()))));
                for i in (0..3000){
                    addr.do_send(ClientCommand( Item::Continue( Bytes::from_iter(buff.clone()))));
                }
                addr.do_send(ClientCommand( Item::Last( Bytes::from_iter(buff.clone()))));
```
Error: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
