### ISSUE TITLE
missing JSDoc to exported functions in std

### ISSUE THREAD

**Issue by tokiedokie** [denoland/deno_std#650] opened 2020-09-15 03:30 UTC
there are many exported functions in standard library but some functions' JSDocs are missing

here is the list of ts files that need to be updated

- [x] `encoding/hex.ts`
- [x] `encoding/toml.ts`
- [x] `fmt/colors.ts`
- [x] `fmt/printf.ts`
- [x] `fs/walk.ts`
- [x] `http/file_server.ts`
- [x] `io/streams.ts`
- [x] `io/util.ts`
- [x] `log/mod.ts`
- [x] `node/querystring.ts`
- [x] `node/url.ts`
- [x] `node/util.ts`
- [x] `path/posix.ts`
- [x] `path/win32.ts`
- [x] `testing/assert.ts`
- [x] `testing/diff.ts`
- [x] `uuid/mod.ts`
- [x] `uuid/v1.ts`
- [x] `uuid/v4.ts`
- [x] `uuid/v5.ts`
- [x] `ws/mod.ts`

**Comment by grian32** [comment] 2021-02-04 04:04
I'll take `io/util.ts` (now knows as `io/ioutil.ts`, maybe that should be updated in the original issue?)

**Comment by bartlomieju** [comment] 2021-11-09 16:54
I'm all in for having JSDocs for all public APIs, the problem is we currently have no way to ensure it automatically. I opened https://github.com/denoland/deno_lint/issues/970 for that purpose.

**Comment by crowlKats** [comment] 2022-12-15 12:26
Closing as this has been completed

**Closed by crowlKats** 2022-12-15 12:26 UTC
Labels: help wanted, ci
