### ISSUE TITLE
datetime: `dayOfYear()` wrong output when date is instantiated with individual date components

### ISSUE THREAD

**Issue by mamereu** [denoland/deno_std#1114] opened 2021-08-08 15:30 UTC
I stumbled on this bug while using dayOfYear inside a loop. Out of [the 4 ways to instantiate a Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date), dayOfYear fails on the fourth one, when individual date components are passed to the constructor, as in the following:

```
dayOfYear(new Date())                        // output 220, ok, today is 08/08/2021
dayOfYear(new Date("2021-08-08"))   // output 220, ok

const unixtime=new Date().getTime()
dayOfYear(new Date(unixtime))         // output 220, ok

dayOfYear(new Date(2021,7,8))         // output 219, wrong !!!  Where has been lost 1 day ? 

//let's go back...
dayOfYear(new Date(2021,0,1))       // output 366, of course should be 1 
dayOfYear(new Date(2021,0,2))      // output 1,  of course should be 2  

```

- OS: fedora 34
```
deno 1.12.2 (release, x86_64-unknown-linux-gnu)
v8 9.2.230.14
typescript 4.3.5
```

**Comment by satyarohith** [comment] 2021-08-08 17:13
Related https://github.com/denoland/deno_std/issues/925

**Comment by iuioiua** [comment] 2022-09-06 07:48
Is this issue fixed by #1384?

**Comment by kt3k** [comment] 2022-09-08 08:42
`dayOfYear` seems handling the given date as UTC. If the system's timezone has the negative offset, `new Date(2021, 0, 1)` becomes 2020-12-31 in UTC. So I think the above examples work as intended

**Comment by lino-levan** [comment] 2022-11-05 05:30
As far as I can tell, this issue was roughly related to the two PRs mentioned, but was never directly a bug and instead just weirdness with time zones. Should this be closed?

**Closed** 2023-06-14 12:26 UTC
Labels: bug
