### ISSUE TITLE
[std/collections] sortBy returns strange result if selector returns NaN sometimes

### ISSUE THREAD

**Issue by kt3k** [denoland/deno_std#1092] opened 2021-08-04 08:15 UTC
Because NaN can't be compared correctly with other numbers, the output becomes broken when the selector returns NaN sometimes.

For example, the following outputs `[NaN, 1, NaN, 5, 7, NaN, 2,   6, 9]`
```ts
import { sortBy } from "./collections/sort_by.ts";

console.log(sortBy([NaN, 1, NaN, 7, NaN, 2, 6, 5, 9], (x) => x));
```

**Comment by kt3k** [comment] 2021-08-04 16:35
Probably `NaN`s should be placed at the end of the array because users should be less interested in `NaN`s than other values.

**Comment by getspooky** [comment] 2021-08-05 08:48
Expected behaviour should be `[1, 2, 5, 6, 7, 9, NaN, NaN, NaN]`

**Comment by getspooky** [comment] 2021-08-05 09:07
I think we should handle `Infinity` and `-Infinity` case.
Current result:
```ts
console.log(sortBy([NaN, 1 , Infinity, NaN, 7, -Infinity, NaN, 2, 6, 5, 9], (x) => x));
// [NaN, -Infinity,1,2, 5, 6, 7, Infinity, NaN, NaN, 9]
```
Exprected result:

```ts
// [-Infinity, 1, 2, 5, 6, 7, 9, Infinity, NaN, NaN, NaN]
```

**Comment by LionC** [comment] 2021-08-05 16:19
Interesting 🤔 The current implementation uses the native `<` behaviour.

I will take a look tonight.

**Comment by LionC** [comment] 2021-08-06 07:01
Hm apparently an MR referencing to this being merged does not close the issue automatically.

@kt3k can you close this?

**Closed** 2021-08-06 11:40 UTC
Labels: needs triage

**Comment by kt3k** [comment] 2021-08-06 11:42
@LionC Thanks! FYI you can use `fix #NNN` directive in PR description to automatically closes corresponding issues.

**Comment by LionC** [comment] 2021-08-06 11:54
> @LionC Thanks! FYI you can use `fix #NNN` directive in PR description to automatically closes corresponding issues.

According to https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue "closes" should work as well (which is what I did). Might be because I do not have the permission to close an issue someone else opened.

**Comment by nayeemrmn** [comment] 2021-08-06 11:55
@LionC It has to be in the description, not the title.
