### ISSUE TITLE
indirect import std log cause app freeze after run

### ISSUE THREAD

**Issue by meepeek** [denoland/deno_std#2397] opened 2022-06-28 17:30 UTC
**Describe the bug**
indirect import https://deno.land/std@0.145.0/log/mod.ts makes the log not working and freeze the program (you will find that running following code will print console but not terminate until you press ctrl-c). Instead, moving import from deps.ts to place directly in test.ts and the problem is gone.

**Steps to Reproduce**
deps.ts
```
export * as log from "https://deno.land/std@0.145.0/log/mod.ts";
```
test.ts
```
import { log } from "./deps.ts";

await log.setup({
  handlers: {
    console: new logger.handlers.ConsoleHandler("DEBUG"),
    file: new logger.handlers.RotatingFileHandler(
      "DEBUG",
      {
        maxBytes: 200000,
        maxBackupCount: 5,
        filename: `./test.txt`,
        formatter: '{levelName} {msg}'
      },
    ),
  },
  loggers: {
    default: {
      level: "DEBUG",
      handlers: ["console"],
    },
    test: {
      level: "DEBUG",
      handlers: ["console", "file"],
    },
  },
});

const logger = log.getLogger("test");

logger.info("test");
log.info("zz");
console.log("a");
```

```
deno run test.ts
```

**Expected behavior**
the program will produce console as follow, but will not end until forced terminate. Also, test.txt will be created but not being written.
```
INFO test
INFO zz
a
^C
```
**Environment**

- OS: MacOS 12.4 on Air M1
- deno version: v8 10.0.139.17 typescript 4.6.2
- std version: ?

**Comment by iuioiua** [comment] 2022-08-21 22:19
Hi @meepeek, are you still running into this issue when using the latest versions of `deno` and `std/log`?

**Comment by lino-levan** [comment] 2022-11-05 05:39
I am completely unable to reproduce this error when I try to make my one reproc.

The bigger issue is that the reproc given straight up doesn't work afaik. Can anyone else reproduce this?

**Comment by meepeek** [comment] 2022-11-06 09:55
@iuioiua I try running with the current deno I have on machine. It no longer freeze.
```
deno 1.27.0 (release, aarch64-apple-darwin)
v8 10.8.168.4
typescript 4.8.3
```
@lino-levan To make the code work, I changed "logger.handlers" to "log.handlers" in log.setup. Can't recall the when I created the issue but it should be naming mistake.

**Comment by iuioiua** [comment] 2022-11-06 10:17
Great to hear! If it's no longer a problem, this issue should be able to be closed 👍🏾

**Comment by cjihrig** [comment] 2022-11-06 14:01
Closing. Thanks!

**Closed by cjihrig** 2022-11-06 14:01 UTC
Labels: bug, needs triage
