### ISSUE TITLE
assertRejects does not fail when an error is thrown, but a promise was not rejected

### ISSUE THREAD

**Issue by dsherret** [denoland/deno_std#1302] opened 2021-09-22 00:49 UTC
**Describe the bug**

```ts
import { assertRejects } from "https://raw.githubusercontent.com/denoland/deno_std/main/testing/asserts.ts";
await assertRejects(function () { throw new Error("test") });
```

**Expected behavior** Should throw because no promise was rejected.

Node's `assertRejects` behaviour:

```
> assert.rejects(function() { throw new Error("test"); }).catch(err => console.log(err));
> Error: test
    at REPL16:1:35
    at waitForActual (assert.js:786:21)
    at Function.rejects (assert.js:921:31)
    at REPL16:1:8
    at Script.runInThisContext (vm.js:134:12)
    at REPLServer.defaultEval (repl.js:486:29)
    at bound (domain.js:416:15)
    at REPLServer.runBound [as eval] (domain.js:427:12)
    at REPLServer.onLine (repl.js:819:10)
    at REPLServer.emit (events.js:387:35)
 ```

This might just be an issue with the renaming from `assertThrowsAsync` -> `assertRejects` and perhaps we should keep `assertThrowsAsync` then change `assertRejects` to assert that a promise is rejected?

**Comment by kt3k** [comment] 2021-09-22 09:22
hmm I'm not sure there's enough needs of the suggested version of `assertRejects`. I personally usually don't distinguish these 2 behaviors when writing async functions..

It feels a little too pedantic to me if we have both `assertReject` and `assertThrowsAsync` with the above difference.

cc @caspervonb 
What do you think about this suggestion?

**Comment by caspervonb** [comment] 2021-09-22 10:22
It does what it says on the tin:
> Executes a function which returns a promise, expecting it to throw or reject.

- Definitively not a bug, does what it is documented to do.
- assertThrowsAsync should never make a return imho, terrible name and the differences are too small.

> `await assertRejects(function () { throw new Error("test") });`

Thinking about this, I'm actually a bit surprised that this isn't a type-error.

I think **maybe** we want this to assert (both at compile time and runtime) that a promise was actually returned, you can always do `Promise.resolve` turn a value into a promise. Seems that is the real source of this category of errors, if the thing is a promise then everything is fine. But in this case it isn't and you can't really assert rejection on a non promise.

**Comment by dsherret** [comment] 2021-09-22 13:17
Here's showing the critical difference between the two and something that will pass type checking:

```ts
function getFunc(throwsSync: boolean) {
  return () => {
    if (throwsSync) {
      throw new Error();
    }

    return Promise.reject(new Error());
  };
}

await assertRejects(getFunc(false)); // pass, ok
await assertRejects(getFunc(true)); // pass, not ok

// why this matters
myFunctionToTest(false).catch(err => { /* ok */ });
myFunctionToTest(false).catch(err => {}); // function throws even though assertRejects tests passed
```

I think we should...

1. Change `assertRejects` to only pass when the function executed returns a promise that rejects.
2. If the function throws and doesn't return a promise that rejects then in addition to failing we should give a bit of an explanatory message to the user.
2. In addition to a function, allow a promise as a parameter for `assertRejects`.

**Comment by bartlomieju** [comment] 2021-11-10 11:00
@dsherret @KyleJune I think your arguments are valid and I'm in favor of changing the behavior of `assertRejects`.

**Comment by Sorikairox** [comment] 2022-05-15 16:28
I was working on it, but I got the following problem : 

With the change, how do we assert async functions that throw instead of returning a rejecting `Promise`?

`assertThrows` is not asynchronous, it only takes a non-async function as a parameter.
I can make it async, but that would be another breaking change on top of this issue breaking change.

**Comment by dsherret** [comment] 2022-05-15 16:41
> With the change, how do we assert async functions that throw instead of returning a rejecting Promise?

I think we can leave `assertThrows` as-is and people could use it for this. Does it not work as-is?

**Comment by Sorikairox** [comment] 2022-05-15 16:48
It sadly doesn't work as-is. `assertThrows` cannot take async functions as parameters.
```ts
Deno.test("testingAssertRejectsWithThrowFailAsItExpectARejection", async () => {
  assertThrows(assertRejects(() => {
    throw new Error();
  }));
});
```
Gives the following error : 

` Argument of type 'Promise<void>' is not assignable to parameter of type '() => unknown'.`

**Comment by dsherret** [comment] 2022-05-15 17:14
@Sorikairox they can use `assertThrows` for functions that throw before returning a promise. async functions return a promise that rejects:

```ts
async function asyncThrow() {
  throw new Error();

  return 5;
}

asyncThrow().catch(err => {}); // does not throw
```

**Comment by Sorikairox** [comment] 2022-05-15 17:20
@dsherret That is my point. You can use `assertThrows` with `syncThrow` but not with `asyncThrow`.
We cannot ask people to rewrite their `async function` to be used with `assertThrows` as they won't be able to use them with `assertRejects` 👀

**Comment by KyleJune** [comment] 2022-05-15 17:21
> With the change, how do we assert async functions that throw instead of returning a rejecting `Promise`? I wanted to test the new `assertRejects` implementation, but it is an async function that throws sweat

Async functions capture thrown errors and turn them into promise rejections. If the function wasn't actually async and just returns a promise normally and it were to throw instead, the `assertRejects` assertion should fail because the function doesn't reject, it throws.

> `assertThrows` is not asynchronous, it only takes a non-async function as a parameter. I can make it async, but that would be another breaking change on top of this issue breaking change.

I think if `assertThrows` returns a rejected promise, it would fail because the function didn't throw. I think that would be desired behavior.

Having this behavior would make it easier to catch and fix issues like errors being thrown incorrectly instead of being rejected and vice versa.

**Comment by dsherret** [comment] 2022-05-15 17:27
> We cannot ask people to rewrite their async function to be used with assertThrows as they won't be able to use them with assertRejects (to check that they throw) anymore after the behavior change brought up by this issue

I think I'm not understanding what you mean. People would continue using `assertRejects` for async functions after this change to my understanding.

**Comment by Sorikairox** [comment] 2022-05-15 17:29
> Async functions capture thrown errors and turn them into promise rejections. If the function wasn't actually async and just returns a promise normally and it were to throw instead, the `assertRejects` assertion should fail because the function doesn't reject, it throws.

It is the behavior I implemented 😄 

But, as I was writing tests for `assertRejects`  new behavior, I could not assert with `assertThrows` that `assertRejects` throws an error because `assertRejects` is an async function and `assertThrows` do not take async functions as parameter.

**Comment by Sorikairox** [comment] 2022-05-15 17:33
> I think I'm not understanding what you mean. People would continue using `assertRejects` for async functions after this change to my understanding.

My bad, I might not be as clear as I think I am.

Before changes : 
- assert that a function throws => use `assertThrows`
- assert that an async function rejects => use `assertRejects`
- assert that an async function throws => use `assertRejects`

After changes: 
- assert that a function throws => use `assertThrows`
- assert that an async function rejects => use `assertRejects`
- assert than an async function throws => cannot use `assertThrows` nor `assertRejects`, what do we do then

**Comment by dsherret** [comment] 2022-05-15 17:38
View async functions as only rejecting a promise because that's what they do.

Before changes :

- assert that a `function` throws => use `assertThrows`
- assert that an `async function` rejects/throws => use `assertRejects`
- assert that a `function` that returns a promise throws synchronously => use `assertThrows`, but right now `assertRejects incorrectly passes

After changes:

- assert that a `function` throws => use `assertThrows`
- assert that an `async function` rejects/throws => use `assertRejects`
- assert that a `function` that returns a promise throws synchronously => use `assertThrows` and `assertRejects` should fail because it throws synchronously

**Comment by Sorikairox** [comment] 2022-05-15 17:45
Okay my bad, I totally missed the point of synchronicity, which was the subject of this issue, and went in an insanely wrong direction.

**Comment by dsherret** [comment] 2022-05-15 17:50
@Sorikairox that's ok! It's a very particular behaviour 😄

No, not a time waste. We're on the same page now and thanks for contributing this!

**Comment by kamilogorek** [comment] 2022-12-18 23:06
Fixed in https://github.com/denoland/deno_std/pull/2234

**Closed** 2022-12-18 23:39 UTC
Labels: enhancement, help wanted
