### ISSUE TITLE
BUG: Prettier check fails on empty files

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_std#298] opened 2019-03-23 13:56 UTC
I have a simple script:
```bash
deno --allow-run --fmt --ignore lib/
```

Output is clean and no file is formatted. However when I add `--check` option it outputs: 
```
deno --allow-run --fmt --ignore lib/ --check
Some files are not formatted
```
I've peeked into `prettier/main.ts` and it seems this line: https://github.com/denoland/deno_std/blob/e80f14489084d748bb52c4311519f5d0c7696f47/prettier/main.ts#L122 should output which files are not formatted, but that's not the case. 

Any ideas @kt3k ?

**Comment by j-f1** [comment] 2019-03-23 15:40
Can you try running Prettier using Node.js to see if it produces an error or something there?

**Comment by kt3k** [comment] 2019-03-23 15:48
@bartlomieju 
I confirmed the bug with v0.3.1. It seems caused by this line https://github.com/denoland/deno_std/blob/c0390ade3de4d825423c9f0f5e1aa56ffd509942/prettier/main.ts#L99
(This should return true)
but because of #241, I think this behavior is now fixed. So can you try your command with --reload option?

**Comment by bartlomieju** [comment] 2019-03-23 16:49
@kt3k I tried it with `--reload` flag, I also tried with:
```
deno --allow-run --allow-write https://deno.land/x/std/prettier/main.ts --ignore lib/
```

Still getting the same error. I'll debug it and get back to you.

**Comment by kt3k** [comment] 2019-03-24 08:43
@bartlomieju Can you share the repository you're experiencing the above behavior? If so, I can look into it.

**Comment by bartlomieju** [comment] 2019-03-24 10:44
Sorry @kt3k got caught up debugging other issue. I can confirm that line you showed above is the problem. It should return true. The bug is visible if you have a file that is empty, then the fail will always fail because it's returning `undefined`.

**Closed** 2019-03-24 15:26 UTC
