### ISSUE TITLE
collections: most functions that work on `Record` do not work with `interface`

### ISSUE THREAD

**Issue by zhangyuannie** [denoland/deno_std#1126] opened 2021-08-12 01:57 UTC
Most of `collections`' functions that work on `Record` do not work with `interface`

**To Reproduce**

```ts
import { deepMerge, filterEntries } from "https://deno.land/std/collections/mod.ts";

interface Foo {
  bar: string;
}

const foo1: Foo = { bar: "deno" };
const foo2: Foo = { bar: "deno" };

const a = deepMerge(foo1, foo2);
const b = filterEntries(foo1, ([key]) => key !== "a");
```

**Expected behavior**

It compiles.

**Current behaviour**

It does not compile.

```
Argument of type 'Foo' is not assignable to parameter of type 'Record<PropertyKey, unknown>'.
      Index signature is missing in type 'Foo'
```

**Desktop (please complete the following information):**

```
deno 1.13.0 (release, x86_64-unknown-linux-gnu)
v8 9.3.345.11
typescript 4.3.5
```
**Additional context**
Possible workaround is to use type instead of interface, but that's not ideal:
```ts
type Foo = {
  bar: string;
}
```

**Comment by LionC** [comment] 2021-08-15 21:45
I think we could fix this with Partial Records. I will take a look at fixing it.

**Comment by LionC** [comment] 2021-08-15 23:46
Having read into this, I realized that  have been down [that rabbit hole](https://github.com/microsoft/TypeScript/issues/15300) before. I do not think there is an easy fix for this without breaking the type promise of the functions.

The problem is that `interface`s can be `extended` and added onto, which makes the index signature that we rely on to have a proper return type very unsafe.

Given

```ts
interface Human { age: number }
interface Developer extends Human { usesVim: boolean }
```

you would expect that passing a `Human` as a `Record<string, number>` should be fine when in fact that `Human` could be a `Developer` with non-`number` values.

This is generally one of the many reasons you should use type aliases over interfaces by default if possible, as they provide stronger guarantees because they can neither be extended nor added onto by arbitrary libraries.
    
There are hacks to pass this - the least ugly of them being spread (`{ ...human }`) fooling the compiler into accepting it - but this ultimately just hides the actual problem.

I do not see a fix for this if we want type signatures to stay helpful.

**Comment by zhangyuannie** [comment] 2021-08-16 03:08
I agree with most however 2 small points:

- Prefer `type` over `interface` is highly debatable. [[1]](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections)[[2]](https://google.github.io/styleguide/tsguide.html#interfaces-vs-type-aliases)
- `type` can also be extended: `type Developer = Human & { usesVim: boolean }`

There isn't an elegant solution, but we can try to augment the type of functions that one might use on interfaces to help our users.

**Comment by getspooky** [comment] 2021-08-18 09:03
@zhangyuannie Something that can help considerably with this issue is to use the following type: 
```ts
type Typify<T> = { [ K in keyof T ]: T[ K ] };
```

Example : 

```ts
import { deepMerge, filterEntries } from "https://deno.land/std/collections/mod.ts";

interface Foo {
  bar: string;
}

type Typify<T> = { [ K in keyof T ]: T[ K ] };

const foo1: Typify<Foo> = { bar: "deno" };
const foo2: Typify<Foo> = { bar: "deno" };

const a = deepMerge(foo1, foo2);
const b = filterEntries(foo1, ([key]) => key !== "a");
```

**Comment by LionC** [comment] 2021-08-18 09:55
> I agree with most, however 2 small points:
> 
> * Prefer `type` over `interface` is highly debatable. [[1]](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections)[[2]](https://google.github.io/styleguide/tsguide.html#interfaces-vs-type-aliases)
> * `type` can also be extended: `type Developer = Human & { usesVim: boolean }`
> 
> There isn't an elegant solution, but we can try to augment the type of functions that one might use on interfaces to help our users.

That is definitely debatable :-)

I do not think there is a reasonable solution on the API side though, so I would vote to close this issue.

**Comment by reckter** [comment] 2021-10-30 11:13
> * `type` can also be extended: `type Developer = Human & { usesVim: boolean }`

This is not the same with the interfaces:



```ts

**Comment by lino-levan** [comment] 2022-10-31 21:14
I think this issue should probably be closed, though the discussion in this issue is very interesting.

**Comment by iuioiua** [comment] 2024-05-08 22:36
Interfaces tend to be used for objects with well-defined shapes, while records tend to be used for objects that are more generic, which aligns with the `std/collections`' design. I'll close this as I think this situation is fine, and there doesn't appear to be an apparent desire to change that. Either way, thank you for the suggestions and input, everyone!

**Closed by iuioiua** 2024-05-08 22:36 UTC
Labels: bug, needs triage
